### ISSUE TITLE
Measure complete latency of a system.

### ISSUE THREAD

**Issue by digitalLumberjack** [pthalin/video_lag_tester#1]
Hello @pthalin !

What a cool project ! I just ordered everything need to create my own video_lag_tester.

I wondered if you though about adding an other feature on the video_lag_tester: having the possibility to measure the complete latency of a console by having a gpio that is triggered while pushing on a controller button, and then waiting for a white screen on the display.

The hdmi would be used only to display the measure.

The detailled process for a super nintendo:
- add a pulled up gpio on the L1 positive connector on the controller (3.3v)
- use the 240P test suite, and go on the black screen of `RGB and white screen` menu
- press L1 to change screen color from black to white
- the calculated lag between the state change on gpio and the white screen will be the complete latency of the system (input lag + process latency + video lag).

We could even make it automatic by controlling the gpio state.

Thanks again for the share of this project !

**Comment by pthalin** [comment]
You would need two screens them since you also need the video from the console. While this is possible I would probably use a different approach with an Arduino and a small display for this. It's much more complicated to develop for an FPGA and it isn't really needed for this.

**Comment by digitalLumberjack** [comment]
Seems relevant. Thank you for your feedback!
